import { Metadata } from "next";
import styles from "./blog.module.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <article
                    className={`mx-auto pv-4 prose dark:prose-invert lg:prose-xl`}
                >
                    {children}
                </article>
            </body>
        </html>
    );
}
