import { Metadata } from "next";
import Navbar from "@/app/(components)/navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div
            className={
                "flex lg:flex-row items-center lg:items-start flex-col min-w-fit max-w-full justify-center"
            }
        >
            <Navbar />
            <article
                className={`container lg:md xl:lg pv-4 prose prose-sm md:prose-base lg:prose-lg xl:prose-xl dark:prose-invert py-8 px-4 lg:px-0`}
            >
                {children}
            </article>
            <div
                className={"w-[calc(100% - 15rem) max-w-[15rem] h-4 flex-grow"}
            ></div>
        </div>
    );
}
