import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                {/* TODO Remove this crap when they fix beforeInteractive */}
                <script
                    id={"dark_mode_default"}
                    dangerouslySetInnerHTML={{
                        __html: `if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  console.log('dark');
                  document.documentElement.classList.add('dark')
                } else {
                  console.log('light');
                  document.documentElement.classList.remove('dark')
                }`,
                    }}
                />
            </head>
            <body
                className={`${inter.className} dark:bg-stone-900 dark:text-white`}
            >
                {children}
            </body>
        </html>
    );
}
