name: "Deploy www.tomfrantz.dev"

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Archive NextJS Production Build
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-export-output-dir
          path: out
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::880397919816:role/tomfrantz_dev_github_role_2
          role-session-name: tomfrantz_dev_github_actions
          aws-region: ap-southeast-2
      - name: Download NextJS Production Build
        uses: actions/download-artifact@v3
        with:
          name: nextjs-export-output-dir
          path: out

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      - run: terraform init
        working-directory: terraform
      - run: terraform apply -auto-approve -input=false
        working-directory: terraform
        env:
          TF_VAR_certificate_arn: ${{ vars.TF_VAR_certificate_arn}}
          TF_VAR_frontend_bucket_name: ${{ vars.TF_VAR_frontend_bucket_name}}
          TF_VAR_hosted_zone_id: ${{ vars.TF_VAR_hosted_zone_id}}
          TF_VAR_domain: ${{ vars.TF_VAR_domain}}
